### ISSUE TITLE
java.net.ConnectException: Connection refused: connect

### ISSUE THREAD

**Issue by pjBooms** [raj-saxena/spring-boot-1-vs-2-performance#1]
I followed your instructions and when executing 

```
gradlew loadTest -D SIM_USERS=5000
```
I've got the following exception in the Spring Boot 2 application on each gatling request:
```
2018-09-05 21:13:57.364 ERROR 19448 --- [o-8080-exec-150] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:8090/register": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect] with root cause
java.net.ConnectException: Connection refused: connect
	at java.base/java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:na]
	at java.base/java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:na]
	at java.base/java.net.PlainSocketImpl.connect(Unknown Source) ~[na:na]
	at java.base/java.net.Socket.connect(Unknown Source) ~[na:na]
	at java.base/java.net.Socket.connect(Unknown Source) ~[na:na]
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[na:na]
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:78) ~[spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:729) ~[spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:686) ~[spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:468) ~[spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at com.xyzz.gsdd.samplespringboot2.services.PersonRegistrationService.addPerson(PersonRegistrationService.kt:17) ~[classes!/:0.0.1-SNAPSHOT]
	at com.xyzz.gsdd.samplespringboot2.controllers.PersonController.addPerson(PersonController.kt:20) ~[classes!/:0.0.1-SNAPSHOT]
```

And Garling also reports that 100% requests were failed.

What do I do wrong?

**Comment by pjBooms** [comment]
I've found the problem. You need to say in README to start backing service in the `person-registration-slow-service` directory with `mvn springboot:run`
